# Generated by Django 5.1.3 on 2024-11-14 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PISU_Auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
